server:
  port: 8094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/saga_db
    username: saga
    password: saga
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

services:
  inventory:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8092}
  payment:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8093}
  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8091}
