server {
    listen 80;
    server_name localhost;

    location /api/orders {
        proxy_pass http://pvip-order-service:8111;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/demo/pause-kafka {
        proxy_pass http://pvip-inventory-service:8112;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/demo/resume-kafka {
        proxy_pass http://pvip-inventory-service:8112;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/demo/kafka-status {
        proxy_pass http://pvip-inventory-service:8112;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/demo {
        proxy_pass http://pvip-order-service:8111;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/products {
        proxy_pass http://pvip-inventory-service:8112;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/customers {
        proxy_pass http://pvip-payment-service:8113;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/transactions {
        proxy_pass http://pvip-commitgate-service:8114;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
